# waybar buttons
windowrulev = float on,match:class blueman-manager nm-connection-editor WiremixApp BtopApp
windowrule = center on,match:class blueman-manager nm-connection-editor WiremixApp BtopApp
windowrule = size 800 600,match:class blueman-manager nm-connection-editor WiremixApp BtopApp

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize

# Fix some dragging issues with XWayland
windowrule = no_focus on,match:xwayland 1,match:float 1,match:fullscreen 0,match:pin 0

# swaync
layerrule = blur on,match:namespace swaync-control-center
layerrule = ignore_alpha 0.5,match:namespace swaync-control-center
layerrule = blur on,match:namespace swaync-notification-window
layerrule = ignore_alpha 0.5,match:namespace swaync-notification-window
