# waybar buttons
windowrulev2 = float, class:^(blueman-manager|nm-connection-editor|WiremixApp|BtopApp)$
windowrulev2 = center, class:^(blueman-manager|nm-connection-editor|WiremixApp|BtopApp)$
windowrulev2 = size 800 600, class:^(blueman-manager|nm-connection-editor|WiremixApp|BtopApp)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# swaync
layerrule = blur, swaync-control-center
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorealpha 0.5, swaync-notification-window
